mybatis:
  typeAliasesPackage: com.liu.eleme.pojo
  mapperLocations: classpath:com/liu/eleme/mapper/*.xml

spring:
  profiles:
    active: dev

---
#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eleme?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
